
global:
  resolve_timeout: 5m
  telegram_api_url: "https://api.telegram.org"

templates:
  - '/etc/alertmanager/templates/telegram.tmpl'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'telegram-notifications'

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '' #Токен
        api_url: 'https://api.telegram.org'
        chat_id: - #Chat ID без кавычек
        parse_mode: 'HTML'
        message: '{{ template "telegram.message" . }}'
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity = critical
    target_matchers:
      - severity = warning
    equal: ['alertname', 'instance']
