version: '3'
services:
  db:
    image: postgres:latest
    container_name: zabbix_db
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data/
    restart: always

  server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix_server
    depends_on:
      - db
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    restart: always
    
  web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix_web
    depends_on:
      - db
      - server
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: server
      PHP_TZ: "Europe/Moscow"
    volumes:
      - zabbix_web:/usr/share/zabbix
    restart: unless-stopped

volumes:
  zabbix_postgres_data:
  zabbix_web:
