# положи в /etc/prometheus/alerts/ или в /etc/prometheus/

groups:
- name: system-alerts
  rules:

  # Алерты на выключение/доступность машины
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} is down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  # Алерты на перегрузку CPU
  - alert: HighCPUUsage
    expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage on {{ $labels.instance }}"
      description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

  - alert: CriticalCPUUsage
    expr: (100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 90
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Critical CPU usage on {{ $labels.instance }}"
      description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

  # Алерты на оперативную память
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage on {{ $labels.instance }}"
      description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

  - alert: CriticalMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 95
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Critical memory usage on {{ $labels.instance }}"
      description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

  # Алерты на дисковое пространство
  - alert: LowDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint!~"/run/.*|/sys/.*|/dev/.*|/proc/.*|/var/lib/docker/.*"} / node_filesystem_size_bytes{mountpoint!~"/run/.*|/sys/.*|/dev/.*|/proc/.*|/var/lib/docker/.*"} * 100) < 20
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Low disk space on {{ $labels.instance }} ({{ $labels.mountpoint }})"
      description: "Disk space is only {{ $value }}% free on {{ $labels.mountpoint }}"

  - alert: CriticalLowDiskSpace
    expr: (node_filesystem_avail_bytes{mountpoint!~"/run/.*|/sys/.*|/dev/.*|/proc/.*|/var/lib/docker/.*"} / node_filesystem_size_bytes{mountpoint!~"/run/.*|/sys/.*|/dev/.*|/proc/.*|/var/lib/docker/.*"} * 100) < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Critical disk space on {{ $labels.instance }} ({{ $labels.mountpoint }})"
      description: "Disk space is only {{ $value }}% free on {{ $labels.mountpoint }}"

  # Алерты на нагрузку системы
  - alert: HighLoadAverage
    expr: node_load5 > (count by(instance) (node_cpu_seconds_total{mode="system"}) * 1.5)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High load average on {{ $labels.instance }}"
      description: "5-minute load average is {{ $value }} on {{ $labels.instance }}"

  # Алерты на swap память
  - alert: HighSwapUsage
    expr: (node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes * 100 > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High swap usage on {{ $labels.instance }}"
      description: "Swap usage is {{ $value }}% on {{ $labels.instance }}"

  # Алерты на количество процессов
  - alert: TooManyProcesses
    expr: node_processes_total > 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Too many processes on {{ $labels.instance }}"
      description: "{{ $value }} processes running on {{ $labels.instance }}"

  # Алерты на user sessions (ваш оригинальный)
  - alert: TooManyActiveUsers
    expr: node_active_users_count > 2
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Too many active user sessions on {{ $labels.instance }}"
      description: "Number of active user sessions is {{ $value }}"

  - alert: CriticalUserSessions
    expr: node_active_users_count > 5
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Critical number of user sessions on {{ $labels.instance }}"
      description: "Number of active user sessions is critically high: {{ $value }}"
